openapi: 3.0.0
servers:
  - description: Test API for Threatlocker
    url: https://api.g.threatlocker.com/api/
info:
  description: Test API for Threatlocker.
  version: 0.4.10
  title: ThreatLocker Portal API
tags:
  - name: public
    description: Operations available to the public
paths:
  /:
    get: rports?list
      tags:
        - public
      summary: Fetches all available Reports for the Organization
      operationId: defaultRoot
      description: |
        By passing in the appropriate options, you can recieve a specific or more than one fact.
      parameters:
        - in: query
          name: reportID
          description: pass an optional id to call a specific report
          required: false
          schema:
            type: string
        - in: query
          name: count
          description: number of facts to return
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1
        - in: query
          name: lang
          description: requested locale to retrieve the cat fact in.
          required: false
          schema:
            type: string
            enum:
              - eng
              - ukr
              - rus
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/fact'
        '400':
          description: bad input parameter
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/error'
        '404':
          description: fact not found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/error'
  
components:
  schemas:
    fact:
      type: object
      properties:
        data:
          type: array
          items:
            type: string
            example: In ancient Egypt, killing a cat was a crime punishable by death.
    error:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 400
        message:
          type: string
          example: Invalid language, valid languages are 'ces', 'eng', 'esp', 'ger', 'rus', 'ukr', 'ces-cz', 'eng-us', 'esp-es', 'esp-mx', 'ger-de', 'rus-ru', 'ukr-au'
        type:
          type: string
          example: Bad Request
